run:
  deadline: 5m
linters:
  enable:
    - vet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - whitespace
    - deadcode
    - unused
    - ineffassign
    - prealloc
    - stylecheck
    - goconst
    - gosimple
    - misspell
    - gosec
  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/futuretea/homelab-webhook
