apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homelab-webhook
  annotations:
    github.com/project-slug: futuretea/homelab-webhook
spec:
  type: other
  lifecycle: unknown
  owner: guests
